"""Rynmesh — verifiable AI content receipt primitives.

Rynmesh is a fully open-source foundation for distributed AI content:
signed run receipts, signed safety receipts, signed manifests, and a
propagation gate honest peers can enforce locally. Third-party attestation
providers can vouch for content via the optional manifest ``attestations``
field without being a required dependency.
"""

__version__ = "0.6.1"

from .credits import (
    CREDIT_LEDGER_VERSION,
    EVENT_WEIGHTS,
    CreditAccount,
    CreditEvent,
    CreditLedgerError,
    CreditPolicy,
    FileCreditLedger,
    default_credit_amount,
    sign_credit_event,
    verify_credit_event,
)
from .crypto import (
    SIGNATURE_ALG,
    SignatureError,
    SignedPayload,
    canonical_json,
    public_key_from_private,
    sha256_bytes,
    sign_payload,
    verify_signed_payload,
)
from .identity import (
    IDENTITY_VERSION,
    IdentityAssessment,
    IdentityError,
    IdentityPolicy,
    IdentityTier,
    PeerVouch,
    ProofOfResource,
    StakeCommitment,
    assess_identity,
    sign_peer_vouch,
    sign_proof_of_resource,
    sign_stake_commitment,
    tier_can_issue,
    tier_distribution_cap,
    verify_peer_vouch,
    verify_proof_of_resource,
    verify_stake_commitment,
)
from .jobs import (
    JobCapacityRecord,
    JobError,
    WorkOrder,
    WorkResult,
    default_expires_at,
    new_work_order_id,
    order_is_open,
    record_within_age,
    sign_job_capacity,
    sign_work_order,
    sign_work_result,
    verify_job_capacity,
    verify_work_order,
    verify_work_result,
)
from .manifest import (
    ManifestError,
    ManifestValidation,
    build_media_asset,
    make_manifest,
    require_propagation_allowed,
    validate_manifest,
)
from .node import PeerError, RynmeshPeer, StoredClip
from .peer_http import HttpPeerClient, PeerTransportError, create_app
from .provenance import (
    LINK_GENESIS,
    LINK_MODEL_ATTESTATION,
    LINK_PEER_ATTESTATION,
    LINK_SAFETY_SCAN,
    LINK_WORK_ENVELOPE,
    PROVENANCE_VERSION,
    ProvenanceError,
    ProvenanceLink,
    ProvenanceVerification,
    append_link,
    chain_head_hash,
    chain_to_payload,
    make_genesis_link,
    sign_link,
    signed_link_hash,
    verify_chain,
)
from .registry import (
    FilePeerRegistry,
    HttpPeerRegistry,
    PeerRecord,
    RegistryError,
    default_peer_registry,
    default_registry_dir,
    sign_peer_record,
    verify_peer_record,
)
from .registry_http import create_app as create_registry_app
from .relay import (
    FileRelayStore,
    HttpRelayClient,
    RelayBlobRecord,
    RelayError,
    file_sha256,
    normalize_content_hash,
)
from .safety import KeywordSafetyScanner, SafetyPolicy, SafetyScanner, sign_safety_receipt
from .store import ClipRecord, RynmeshStore, StoreError, default_network_dir, default_rynmesh_home
from .types import (
    RYNMESH_VERSION,
    ClipManifest,
    MediaAsset,
    RunReceipt,
    SafetyOutcome,
    SafetyReceipt,
)

__all__ = [
    "__version__",
    "RYNMESH_VERSION",
    "SIGNATURE_ALG",
    "RunReceipt",
    "ClipManifest",
    "ClipRecord",
    "CREDIT_LEDGER_VERSION",
    "CreditAccount",
    "CreditEvent",
    "CreditLedgerError",
    "CreditPolicy",
    "EVENT_WEIGHTS",
    "FilePeerRegistry",
    "FileCreditLedger",
    "FileRelayStore",
    "HttpPeerRegistry",
    "HttpPeerClient",
    "HttpRelayClient",
    "IDENTITY_VERSION",
    "IdentityAssessment",
    "IdentityError",
    "IdentityPolicy",
    "IdentityTier",
    "JobCapacityRecord",
    "JobError",
    "KeywordSafetyScanner",
    "LINK_GENESIS",
    "LINK_MODEL_ATTESTATION",
    "LINK_PEER_ATTESTATION",
    "LINK_WORK_ENVELOPE",
    "LINK_SAFETY_SCAN",
    "ManifestError",
    "ManifestValidation",
    "MediaAsset",
    "PROVENANCE_VERSION",
    "PeerError",
    "PeerRecord",
    "PeerTransportError",
    "PeerVouch",
    "ProofOfResource",
    "ProvenanceError",
    "ProvenanceLink",
    "ProvenanceVerification",
    "RelayBlobRecord",
    "RelayError",
    "RegistryError",
    "RynmeshPeer",
    "RynmeshStore",
    "SafetyOutcome",
    "SafetyPolicy",
    "SafetyReceipt",
    "SafetyScanner",
    "SignatureError",
    "SignedPayload",
    "StakeCommitment",
    "StoredClip",
    "StoreError",
    "WorkOrder",
    "WorkResult",
    "append_link",
    "assess_identity",
    "build_media_asset",
    "canonical_json",
    "chain_head_hash",
    "chain_to_payload",
    "create_app",
    "create_registry_app",
    "default_credit_amount",
    "default_expires_at",
    "default_network_dir",
    "default_peer_registry",
    "default_registry_dir",
    "default_rynmesh_home",
    "file_sha256",
    "make_genesis_link",
    "make_manifest",
    "new_work_order_id",
    "normalize_content_hash",
    "order_is_open",
    "public_key_from_private",
    "record_within_age",
    "require_propagation_allowed",
    "sha256_bytes",
    "sign_credit_event",
    "sign_job_capacity",
    "sign_link",
    "sign_payload",
    "sign_peer_record",
    "sign_peer_vouch",
    "sign_proof_of_resource",
    "sign_safety_receipt",
    "sign_stake_commitment",
    "sign_work_order",
    "sign_work_result",
    "signed_link_hash",
    "tier_can_issue",
    "tier_distribution_cap",
    "validate_manifest",
    "verify_chain",
    "verify_credit_event",
    "verify_job_capacity",
    "verify_peer_record",
    "verify_peer_vouch",
    "verify_proof_of_resource",
    "verify_signed_payload",
    "verify_stake_commitment",
    "verify_work_order",
    "verify_work_result",
]
